// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackerKerja.Data;

#nullable disable

namespace TrackerKerja.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260819032206_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("TrackerKerja.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#6366F1",
                            Name = "Backend"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#06B6D4",
                            Name = "Frontend"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#10B981",
                            Name = "API / REST"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#F59E0B",
                            Name = "Database"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#EF4444",
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#8B5CF6",
                            Name = "Testing"
                        });
                });

            modelBuilder.Entity("TrackerKerja.Models.JsonHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("JsonHistories");
                });

            modelBuilder.Entity("TrackerKerja.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#6366F1",
                            CreatedAt = new DateTime(2026, 8, 19, 10, 22, 6, 69, DateTimeKind.Local).AddTicks(2328),
                            Deadline = new DateTime(2026, 10, 19, 10, 22, 6, 69, DateTimeKind.Local).AddTicks(2318),
                            Description = "Aplikasi tracker kerja all-in-one",
                            Name = "Work Tracker Pro",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Color = "#10B981",
                            CreatedAt = new DateTime(2026, 8, 19, 10, 22, 6, 69, DateTimeKind.Local).AddTicks(2332),
                            Deadline = new DateTime(2026, 9, 19, 10, 22, 6, 69, DateTimeKind.Local).AddTicks(2331),
                            Description = "Integrasi REST API dengan sistem eksternal",
                            Name = "REST API Integration",
                            Status = 0
                        });
                });

            modelBuilder.Entity("TrackerKerja.Models.WorkSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("TrackerKerja.Models.WorkTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 8, 19, 10, 22, 6, 69, DateTimeKind.Local).AddTicks(2363),
                            Description = "Inisialisasi project dengan EF Core dan SQLite",
                            DueDate = new DateTime(2026, 8, 20, 10, 22, 6, 69, DateTimeKind.Local).AddTicks(2359),
                            Priority = 2,
                            ProjectId = 1,
                            Status = 2,
                            Title = "Setup Project ASP.NET Core MVC",
                            UpdatedAt = new DateTime(2026, 8, 19, 10, 22, 6, 69, DateTimeKind.Local).AddTicks(2364)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 8, 19, 10, 22, 6, 69, DateTimeKind.Local).AddTicks(2368),
                            Description = "Membuat tampilan dashboard dengan Tailwind CSS",
                            DueDate = new DateTime(2026, 8, 22, 10, 22, 6, 69, DateTimeKind.Local).AddTicks(2367),
                            Priority = 2,
                            ProjectId = 1,
                            Status = 1,
                            Title = "Design UI Dashboard",
                            UpdatedAt = new DateTime(2026, 8, 19, 10, 22, 6, 69, DateTimeKind.Local).AddTicks(2368)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 8, 19, 10, 22, 6, 69, DateTimeKind.Local).AddTicks(2371),
                            Description = "Mempelajari dan mendokumentasikan endpoint REST",
                            DueDate = new DateTime(2026, 8, 24, 10, 22, 6, 69, DateTimeKind.Local).AddTicks(2370),
                            Priority = 1,
                            ProjectId = 2,
                            Status = 0,
                            Title = "Analisis endpoint REST API",
                            UpdatedAt = new DateTime(2026, 8, 19, 10, 22, 6, 69, DateTimeKind.Local).AddTicks(2371)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 8, 19, 10, 22, 6, 69, DateTimeKind.Local).AddTicks(2374),
                            Description = "Memverifikasi format response JSON dari API",
                            DueDate = new DateTime(2026, 8, 26, 10, 22, 6, 69, DateTimeKind.Local).AddTicks(2374),
                            Priority = 1,
                            ProjectId = 2,
                            Status = 0,
                            Title = "Testing JSON Response Format",
                            UpdatedAt = new DateTime(2026, 8, 19, 10, 22, 6, 69, DateTimeKind.Local).AddTicks(2375)
                        });
                });

            modelBuilder.Entity("TrackerKerja.Models.JsonHistory", b =>
                {
                    b.HasOne("TrackerKerja.Models.WorkTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TrackerKerja.Models.WorkSession", b =>
                {
                    b.HasOne("TrackerKerja.Models.WorkTask", "Task")
                        .WithMany("Sessions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TrackerKerja.Models.WorkTask", b =>
                {
                    b.HasOne("TrackerKerja.Models.Category", "Category")
                        .WithMany("Tasks")
                        .HasForeignKey("CategoryId");

                    b.HasOne("TrackerKerja.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Category");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TrackerKerja.Models.Category", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TrackerKerja.Models.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TrackerKerja.Models.WorkTask", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
